#!/bin/bash

#This command does not have a fucking main_ undefined error using linker.
kos32-ld SDLTest.o -T/home/bob/kolibrios/contrib/sdk/sources/newlib/libc/app.lds -nostdlib -static --image-base 0 -lgcc -L/home/autobuild/tools/win32/mingw32/lib /home/autobuild/tools/win32/lib/libdll.a /home/autobuild/tools/win32/lib/libapp.a /home/autobuild/tools/win32/lib/libSDL.a /home/autobuild/tools/win32/lib/libc.dll.a -static -o sdltest

#kos32-gcc -c -I/home/bob/dev-netsurf/workspace/netsurf/kolibrios -I/home/bob/kolibrios/contrib/sdk/sources/newlib/libc/include -I/home/bob/dev-netsurf/workspace/inst-i686-linux-gnu/include  -I/home/bob/kolibrios/contrib/sdk/sources/zlib  -std=c99 -D_KOLIBRIOS -Dnskolibrios -g   -Wundef   -U_Win32 -U_WIN32 -U__MINGW32__   -U__BSD_VISIBLE   -D_BSD_SOURCE   -D_DEFAULT_SOURCE   -D_XOPEN_SOURCE=700   -D_POSIX_C_SOURCE=200809L   -D_NETBSD_SOURCE   -U HAVE_UTSN‚ME main.c kolibri_debug.c

#kos32-ld -T/home/bob/kolibrios/contrib/sdk/sources/newlib/libc/app.lds -nostdlib -L/home/autobuild/tools/win32/mingw32/lib /home/autobuild/tools/win32/lib/libz.a /home/autobuild/tools/win32/lib/libdll.a /home/autobuild/tools/win32/lib/libapp.a /home/autobuild/tools/win32/lib/libc.dll.a /home/autobuild/tools/win32/lib/libiberty.a -lgcc kolibri_debug.o main.o -o main_bin


#kos32-gcc -c -I/home/bob/kolibrios/contrib/sdk/sources/newlib/libc/include -I/home/bob/kolibrios/contrib/sdk/sources/zlib  -std=c99 -D_KOLIBRIOS -Dnskolibrios -g   -Wundef   -U_Win32 -U_WIN32 -U__MINGW32__   -U__BSD_VISIBLE   -D_BSD_SOURCE   -D_DEFAULT_SOURCE   -D_XOPEN_SOURCE=700   -D_POSIX_C_SOURCE=200809L   -D_NETBSD_SOURCE   -U HAVE_UTSN‚ME main.c -o main.o

kos32-ld -T/home/bob/kolibrios/contrib/sdk/sources/newlib/libc/app.lds -nostdlib -L/home/autobuild/tools/win32/mingw32/lib /home/autobuild/tools/win32/lib/libz.a /home/autobuild/tools/win32/lib/libc.dll.a /home/autobuild/tools/win32/lib/libapp.a /home/autobuild/tools/win32/lib/libdll.a  /home/autobuild/tools/win32/lib/libiberty.a -lgcc main.o *.o ~/ofiles/*.o *.obj -o netsurfer
